# Generated by Django 5.1.5 on 2025-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Полное наименование компании (ООО ...)')),
                ('shortname', models.CharField(max_length=250, verbose_name='Короткое наименование компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип компании')),
                ('shortdescription', models.TextField(verbose_name='Короткое описание компании')),
                ('shortdescription_ru', models.TextField(null=True, verbose_name='Короткое описание компании')),
                ('shortdescription_en', models.TextField(null=True, verbose_name='Короткое описание компании')),
                ('office_address', models.CharField(max_length=250, verbose_name='Адрес главного офиса')),
                ('office_address_ru', models.CharField(max_length=250, null=True, verbose_name='Адрес главного офиса')),
                ('office_address_en', models.CharField(max_length=250, null=True, verbose_name='Адрес главного офиса')),
                ('office_address_map_link', models.TextField(blank=True, null=True, verbose_name='Ссылка на карту адреса главного офиса')),
                ('telegram', models.CharField(max_length=100, verbose_name='Ссылка на Telegram')),
                ('instagram', models.CharField(max_length=100, verbose_name='Ссылка на Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Facebook')),
                ('email', models.CharField(max_length=100, verbose_name='Email поддержки')),
                ('phone_1', models.CharField(max_length=20, verbose_name='Номер телефона 1 (просто цифры)')),
                ('phone_2', models.CharField(max_length=20, verbose_name='Номер телефона 2 (просто цифры)')),
                ('phone_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 3 (просто цифры)')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Данные актуальны')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название магазина')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Название магазина')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес магазина')),
                ('address_ru', models.CharField(max_length=250, null=True, verbose_name='Адрес магазина')),
                ('address_en', models.CharField(max_length=250, null=True, verbose_name='Адрес магазина')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Facebook')),
                ('phone_1', models.CharField(max_length=20, verbose_name='Номер телефона 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 2')),
                ('phone_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 3')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
