# Generated by Django 5.1.5 on 2025-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 2 (просто цифры)'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Telegram'),
        ),
    ]
