# Generated by Django 5.1.5 on 2025-04-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя потенциального клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки запроса')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Заявка обработана')),
                ('date_checked', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки заявки')),
                ('status', models.CharField(blank=True, choices=[('positive', 'Потенциальный клиент'), ('negative', 'Не готов сотрудничать'), ('recall', 'Просили перезвонить'), ('mistake', 'Ошиблись/Недопонимание'), ('spam', 'Спам/Реклама'), ('need_more_time', 'Нужно время на подумать'), ('question', 'Просто задать вопрос'), ('another', 'Другое (указать в поле "Комментарий")')], max_length=100, null=True, verbose_name='Статус ответа клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_to_recall', models.DateField(blank=True, null=True, verbose_name='Дата перезвона клиенту')),
            ],
            options={
                'verbose_name': 'Запрос на звонок',
                'verbose_name_plural': 'Запросы на звонок',
            },
        ),
    ]
