# Generated by Django 5.1.5 on 2025-08-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'permissions': [('view_callrequest_list', 'Can see call requests list')], 'verbose_name': 'Запрос на звонок', 'verbose_name_plural': 'Запросы на звонок'},
        ),
    ]
