# Generated by Django 5.1.5 on 2026-03-13 13:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_add_custom_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_first', models.CharField(blank=True, max_length=30, null=True, verbose_name='Первый телефон')),
                ('phone_second', models.CharField(blank=True, max_length=30, null=True, verbose_name='Второй телефон')),
                ('phone_third', models.CharField(blank=True, max_length=30, null=True, verbose_name='Третий телефон')),
                ('telegram_link', models.TextField(blank=True, null=True, verbose_name='Telegram ссылка')),
                ('telegram_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telegram имя')),
                ('vk_link', models.TextField(blank=True, null=True, verbose_name='VK ссылка')),
                ('vk_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='VK имя')),
                ('instagram_link', models.TextField(blank=True, null=True, verbose_name='Instagram ссылка')),
                ('instagram_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Instagram имя')),
                ('is_main_office', models.BooleanField(default=False, verbose_name='Главный офис')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('map_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Координаты на карте')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalShop',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_first', models.CharField(blank=True, max_length=30, null=True, verbose_name='Первый телефон')),
                ('phone_second', models.CharField(blank=True, max_length=30, null=True, verbose_name='Второй телефон')),
                ('phone_third', models.CharField(blank=True, max_length=30, null=True, verbose_name='Третий телефон')),
                ('telegram_link', models.TextField(blank=True, null=True, verbose_name='Telegram ссылка')),
                ('telegram_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telegram имя')),
                ('vk_link', models.TextField(blank=True, null=True, verbose_name='VK ссылка')),
                ('vk_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='VK имя')),
                ('instagram_link', models.TextField(blank=True, null=True, verbose_name='Instagram ссылка')),
                ('instagram_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Instagram имя')),
                ('is_main_office', models.BooleanField(default=False, verbose_name='Главный офис')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('map_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Координаты на карте')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_shop', to='administration.shop')),
            ],
            options={
                'verbose_name': 'historical Магазин',
                'verbose_name_plural': 'historical Магазины',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
