# Generated by Django 5.1.5 on 2026-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('view_shop_list', 'Can see Shops list'),), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='historicalshop',
            name='phone_first',
            field=models.CharField(max_length=30, verbose_name='Первый телефон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_first',
            field=models.CharField(max_length=30, verbose_name='Первый телефон'),
        ),
    ]
