# Generated by Django 5.1.5 on 2026-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_shop_options_alter_historicalshop_phone_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshop',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
