# Generated by Django 5.1.5 on 2026-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_historicalshop_name_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshop',
            name='city',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
    ]
