# Generated by Django 5.1.5 on 2026-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_historicalshop_city_alter_shop_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalshop',
            name='address',
            field=models.TextField(db_index=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(unique=True, verbose_name='Адрес'),
        ),
    ]
