# Generated by Django 5.1.5 on 2026-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_shop_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если магазин не активен, он не будет отображаться в списке магазинов', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если магазин не активен, он не будет отображаться в списке магазинов', verbose_name='Активен'),
        ),
    ]
