# Generated by Django 5.1.5 on 2026-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_historicalshop_is_active_shop_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian', models.CharField(help_text='От 40 до 52', max_length=8, verbose_name='Российский размер')),
                ('international', models.CharField(help_text='Например: XXS, XS, S, M, L, XL, XXL', max_length=8, verbose_name='Международный размер')),
                ('european', models.CharField(help_text='От 34 до 46', max_length=8, verbose_name='Европейский размер')),
                ('chest_circumference', models.CharField(help_text='От 80 до 104', max_length=8, verbose_name='Обхват груди (см)')),
                ('waist_circumference', models.CharField(help_text='От 60 до 86', max_length=8, verbose_name='Обхват талии (см)')),
                ('hip_circumference', models.CharField(help_text='От 86 до 112', max_length=8, verbose_name='Обхват бедер (см)')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'permissions': (('view_size_list', 'Can see Sizes list'),),
            },
        ),
    ]
