# Generated by Django 5.1.5 on 2026-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
    ]
