# Generated by Django 5.1.5 on 2026-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_size_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядок'),
        ),
    ]
