# Generated by Django 5.1.5 on 2026-03-14 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_size_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Основные цвета, Пастельные тона и т.д.', max_length=100, verbose_name='Название')),
                ('color', models.CharField(help_text='HEX-код цвета (например: #FF5733)', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный HEX-код цвета (например: #FF5733 или #F00)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли этот цвет в палитре', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Цвет палитры',
                'verbose_name_plural': 'Цвета палитры',
            },
        ),
    ]
