# Generated by Django 5.1.5 on 2026-03-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_colorpalette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorpalette',
            options={'permissions': (('view_colorpalette_list', 'Can see ColorPalettes list'),), 'verbose_name': 'Цвет палитры', 'verbose_name_plural': 'Цвета палитры'},
        ),
    ]
