# Generated by Django 5.1.5 on 2026-03-14 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_alter_colorpalette_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='color',
            field=models.CharField(help_text='Формат: #RRGGBB (например: #FF5733)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный 6-значный HEX-код цвета (например: #FF5733)', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='HEX-код'),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='name',
            field=models.CharField(help_text='Например: Основные цвета, Пастельные тона и т.д.', max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
