# Generated by Django 5.1.5 on 2026-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_colorpalette_color_alter_colorpalette_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_custom_product_settings', models.BooleanField(default=True, verbose_name='Использовать кастомные настройки товаров')),
                ('is_all_colors_same_name', models.BooleanField(default=False, verbose_name='Все цвета имеют одинаковое название')),
                ('is_all_colors_same_price', models.BooleanField(default=False, verbose_name='Все цвета имеют одинаковую цену')),
                ('is_all_colors_same_description', models.BooleanField(default=False, verbose_name='Все цвета имеют одинаковое описание')),
                ('is_all_colors_same_model', models.BooleanField(default=False, verbose_name='Все цвета имеют одинаковую модель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'constraints': [models.CheckConstraint(condition=models.Q(('id__lte', 1)), name='single_settings_record')],
            },
        ),
    ]
