# Generated by Django 5.1.5 on 2026-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshop',
            name='map_location',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='map_location',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
