# Generated by Django 5.1.5 on 2026-03-20 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_historicalshop_map_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorpalette',
            old_name='color',
            new_name='hex',
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='hex',
            field=models.CharField(
                help_text='Формат: #RRGGBB (например: #FF5733)',
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Введите корректный 6-значный HEX-код цвета (например: #FF5733)',
                        regex='^#([A-Fa-f0-9]{6})$'
                    )
                ],
                verbose_name='HEX код'
            ),
        ),
    ]