# Generated by Django 5.1.5 on 2026-03-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_alter_colorpalette_color_colorpalette_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='updated_at',
            new_name='date_updated',
        ),
    ]
