# Generated by Django 5.1.5 on 2026-03-27 13:09

import administration.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_alter_productcategory_creator_productcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='is_all_colors_same_description',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='is_all_colors_same_model',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='is_all_colors_same_name',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='is_all_colors_same_price',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='set_custom_product_settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='is_all_products_same_description',
            field=models.BooleanField(default=False, verbose_name='Все товары имеют одинаковое описание'),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_all_products_same_model',
            field=models.BooleanField(default=False, verbose_name='Все товары имеют одинаковую модель'),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_all_products_same_name',
            field=models.BooleanField(default=False, verbose_name='Все товары имеют одинаковое название'),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_all_products_same_price',
            field=models.BooleanField(default=False, verbose_name='Все товары имеют одинаковую цену'),
        ),
        migrations.AddField(
            model_name='settings',
            name='set_custom_product_card_settings',
            field=models.BooleanField(default=True, verbose_name='Использовать кастомные настройки карточки товаров'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=250, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('color_name', models.CharField(max_length=250, verbose_name='Название цвета')),
                ('color_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Код цвета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('model_params', models.JSONField(blank=True, null=True, validators=[administration.models.Product.validate_model_params], verbose_name='Параметры модели')),
                ('material_and_care', models.TextField(blank=True, null=True, verbose_name='Материал и уход')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.productcard', verbose_name='Карточка товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'permissions': (('view_product_list', 'Can see Products list'),),
                'unique_together': {('product_card', 'color_name')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=250, verbose_name='Артикул')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('color_name', models.CharField(max_length=250, verbose_name='Название цвета')),
                ('color_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Код цвета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('model_params', models.JSONField(blank=True, null=True, validators=[administration.models.Product.validate_model_params], verbose_name='Параметры модели')),
                ('material_and_care', models.TextField(blank=True, null=True, verbose_name='Материал и уход')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.productcard', verbose_name='Карточка товара')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_product', to='administration.product')),
            ],
            options={
                'verbose_name': 'historical Товар',
                'verbose_name_plural': 'historical Товары',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_all_products_same_name', models.BooleanField(default=True, verbose_name='Все товары имеют одинаковое название')),
                ('is_all_products_same_price', models.BooleanField(default=True, verbose_name='Все товары имеют одинаковую цену')),
                ('is_all_products_same_description', models.BooleanField(default=True, verbose_name='Все товары имеют одинаковое описание')),
                ('is_all_products_same_model', models.BooleanField(default=True, verbose_name='Все товары имеют одинаковую модель')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.productcard', verbose_name='Карточка товара')),
            ],
            options={
                'verbose_name': 'Настройки карточки товара',
                'verbose_name_plural': 'Настройки карточек товаров',
                'permissions': (('view_productcardsettings_list', 'Can see Product Card Settings list'),),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Изображение')),
                ('preview', models.ImageField(upload_to='products/previews/', verbose_name='Превью')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'permissions': (('view_productimage_list', 'Can see Product Images list'),),
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shop')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.size')),
            ],
            options={
                'verbose_name': 'Склад товара',
                'verbose_name_plural': 'Склады товаров',
                'permissions': (('view_productstock_list', 'Can see Product Stock list'),),
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'shop'), name='unique_product_size_shop_stock')],
            },
        ),
    ]
