# Generated by Django 5.1.5 on 2026-03-28 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_remove_settings_is_all_colors_same_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_categories/covers/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='administration.productcategory', verbose_name='Категория')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Обложка категории',
                'verbose_name_plural': 'Обложки категорий',
                'permissions': (('view_productcategorycover_list', 'Can see Product Category Covers list'),),
                'unique_together': {('category', 'order')},
            },
        ),
    ]
