# Generated by Django 5.1.5 on 2026-03-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_productcategorycover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductcategory',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='cover',
        ),
    ]
