# Generated by Django 5.1.5 on 2026-03-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_remove_historicalproductcategory_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorycover',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='administration.productcategory', verbose_name='Категория'),
        ),
    ]
