# Generated by Django 5.1.5 on 2026-03-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_alter_productcategorycover_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategorycover',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productcategorycover',
            name='order',
        ),
    ]
