# Generated by Django 5.1.5 on 2026-03-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0025_alter_productcategorycover_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.productcategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.productcategory', verbose_name='Родительская категория'),
        ),
    ]
