# Generated by Django 5.1.5 on 2026-03-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_alter_historicalproductcategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
    ]
