# Generated by Django 5.1.5 on 2026-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_alter_productcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductcard',
            name='is_all_products_same_description',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковое описание'),
        ),
        migrations.AddField(
            model_name='historicalproductcard',
            name='is_all_products_same_model',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковую модель'),
        ),
        migrations.AddField(
            model_name='historicalproductcard',
            name='is_all_products_same_name',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковое название'),
        ),
        migrations.AddField(
            model_name='historicalproductcard',
            name='is_all_products_same_price',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковую цену'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='is_all_products_same_description',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковое описание'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='is_all_products_same_model',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковую модель'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='is_all_products_same_name',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковое название'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='is_all_products_same_price',
            field=models.BooleanField(default=True, verbose_name='Все товары имеют одинаковую цену'),
        ),
        migrations.DeleteModel(
            name='ProductCardSettings',
        ),
    ]
