# Generated by Django 5.1.5 on 2026-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_historicalproductcard_is_all_products_same_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='set_custom_product_card_settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='set_global_product_card_settings',
            field=models.BooleanField(default=True, verbose_name='Использовать общие настройки карточки товаров'),
        ),
    ]
