# Generated by Django 5.1.5 on 2026-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_remove_settings_set_custom_product_card_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='products/previews/', verbose_name='Превью'),
        ),
    ]
