# Generated by Django 5.1.5 on 2026-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_custom_color',
            field=models.BooleanField(default=False, verbose_name='Является ли цвет пользовательским (не из палитры)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_color',
            field=models.BooleanField(default=False, verbose_name='Является ли цвет пользовательским (не из палитры)'),
        ),
    ]
