# Generated by Django 5.1.5 on 2026-03-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_historicalproduct_is_custom_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='color_code',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='color',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.colorpalette', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.colorpalette', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administration.product', verbose_name='Товар'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_code',
        ),
    ]
