# Generated by Django 5.1.5 on 2026-03-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_product_unique_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'permissions': (('view_productstock_list', 'Can see Product Stock list'),), 'verbose_name': 'Учет товара', 'verbose_name_plural': 'Учет товаров'},
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='number',
        ),
        migrations.AddField(
            model_name='productstock',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='administration.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.size', verbose_name='Размер'),
        ),
    ]
