# Generated by Django 5.1.5 on 2026-03-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_alter_productstock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.productcard', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.productcategory', verbose_name='Родительская категория'),
        ),
    ]
