# Generated by Django 5.1.5 on 2026-03-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_alter_product_product_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='administration.productcard', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='categories',
            field=models.ManyToManyField(related_name='product_cards', to='administration.productcategory', verbose_name='Категории'),
        ),
    ]
