# Generated by Django 5.1.5 on 2025-05-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название параметра')),
                ('name_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название параметра')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название параметра')),
            ],
            options={
                'verbose_name': 'Измерение продукта',
                'verbose_name_plural': 'Измерения продуктов',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название (мм, см, м, кг...)')),
                ('name_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название (мм, см, м, кг...)')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название (мм, см, м, кг...)')),
            ],
            options={
                'verbose_name': 'Мера измерения',
                'verbose_name_plural': 'Меры измерений',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название категории товара')),
                ('name_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название категории товара')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название категории товара')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('photo', models.ImageField(upload_to='product_categories/', verbose_name='Фото категории (1:1)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='product_categories/covers/', verbose_name='Обложка страницы (16:9)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Показывать в системе')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название товара')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Название товара')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('price', models.FloatField(default=0, verbose_name='Цена товара')),
                ('sale_price', models.FloatField(default=0, verbose_name='Цена товара со скидкой')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание товара (показывается в карточке товара, 250 символов)')),
                ('description_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание товара (показывается в карточке товара, 250 символов)')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание товара (показывается в карточке товара, 250 символов)')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('description_short_ru', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('description_short_en', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Показывать в системе')),
                ('categories', models.ManyToManyField(blank=True, to='marketplace.productcategory', verbose_name='Категории продукта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение параметра')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Показывать в системе')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.measurementtype', verbose_name='Параметр продукта')),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.measurementunit', verbose_name='Мера измерения параметра')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Параметр товара',
                'verbose_name_plural': 'Параметры товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Номер фото по порядку')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Показывать в системе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название тега товара')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Название тега товара')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Название тега товара')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Показывать в системе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.productcategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Тег товара',
                'verbose_name_plural': 'Теги товаров',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='marketplace.producttag', verbose_name='Теги продукта'),
        ),
    ]
