# Generated by Django 5.1.5 on 2025-10-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(upload_to='product_categories/', verbose_name='Photo (1:1)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='product_categories/covers/', verbose_name='Category cover (16:9)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is_actial')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'permissions': [('view_productcategory_list', 'Can see product categories list')],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tags/', verbose_name='Photo')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is_actual')),
            ],
            options={
                'verbose_name': 'Product tag',
                'verbose_name_plural': 'Product tags',
                'permissions': [('view_producttag_list', 'Can see product tags list')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Articul')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
                ('sale_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Sale price')),
                ('description_short', models.CharField(blank=True, max_length=250, null=True, verbose_name='Short description (up to 250 symbols)')),
                ('description_short_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Short description (up to 250 symbols)')),
                ('description_short_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Short description (up to 250 symbols)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is_actual')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('categories', models.ManyToManyField(blank=True, to='marketplace.productcategory', verbose_name='Categories')),
                ('tags', models.ManyToManyField(blank=True, to='marketplace.producttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'permissions': [('view_product_list', 'Can see products list')],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color (HEX form.)')),
                ('name', models.CharField(max_length=150, verbose_name='Color name')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is_actual')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product color',
                'verbose_name_plural': 'Product colors',
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Photo')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Order number')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is_actual')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product photo',
                'verbose_name_plural': 'Product photo',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Size name')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is_actual')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.productcolor', verbose_name='Product color')),
            ],
            options={
                'verbose_name': 'Product size',
                'verbose_name_plural': 'Product sizes',
                'unique_together': {('color', 'size')},
            },
        ),
    ]
