# Generated by Django 5.1.5 on 2025-06-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_date_created_productcategory_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание товара (показывается в карточке товара, 250 символов)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание товара (показывается в карточке товара, 250 символов)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание товара (показывается в карточке товара, 250 символов)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
