# Generated by Django 5.1.5 on 2025-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=250, verbose_name='Значение параметра'),
        ),
    ]
