# Generated by Django 5.1.5 on 2025-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_productparameter_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название тега товара'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название тега товара'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_en',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название тега товара'),
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='category',
        ),
    ]
