# Generated by Django 5.1.5 on 2025-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_producttag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_product_list', 'Can see products list')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'permissions': [('view_productcategory_list', 'Can see product categories list')], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'permissions': [('view_producttag_list', 'Can see product tags list')], 'verbose_name': 'Тег товара', 'verbose_name_plural': 'Теги товаров'},
        ),
    ]
