from .doc import (
    ADMINISTRATION_PATHS,
    ADMINISTRATION_SCHEMAS,
    ADMINISTRATION_TAG,
    ADMINISTRATION_TAGS,
    ADMINISTRATION_X_TAG_GROUPS,
)

__all__ = [
    "ADMINISTRATION_PATHS",
    "ADMINISTRATION_SCHEMAS",
    "ADMINISTRATION_TAG",
    "ADMINISTRATION_TAGS",
    "ADMINISTRATION_X_TAG_GROUPS",
]
