# Generated by Django 5.1.5 on 2025-05-22 21:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона в формате +7(XX) XXX XXXX', max_length=128, region='RU', unique=True),
        ),
    ]
