# Generated by Django 5.1.5 on 2026-03-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], max_length=10, verbose_name='Метод запроса')),
                ('old_value', models.JSONField(default=dict, verbose_name='Старое значение')),
                ('new_value', models.JSONField(default=dict, verbose_name='Новое значение')),
                ('serializer_class', models.CharField(max_length=250, null=True, verbose_name='Название класса сериализатора')),
                ('model_name', models.CharField(max_length=250, null=True, verbose_name='Наименование модели')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
