# Generated by Django 5.1.5 on 2025-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'employee'), ('email__isnull', False)), fields=('email',), name='unique_employee_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'client'), ('phone__isnull', False)), fields=('phone',), name='unique_client_phone'),
        ),
    ]
