# Generated by Django 5.1.5 on 2026-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
    ]
