# Generated by Django 5.1.5 on 2025-05-22 21:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_unique_employee_email_user_unique_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона в формате +7 (XXX) XXX XXXX', max_length=128, null=True, region='RU', unique=True),
        ),
    ]
