# Generated by Django 5.1.5 on 2026-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='Метод запроса'),
        ),
    ]
