# Generated by Django 5.1.5 on 2026-03-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_requestlog_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'permissions': (('view_requestlog_list', 'Can see Request log list'),), 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
